### ISSUE TITLE
Create a external style sheet with some basic colors to common HTML elements

### ISSUE THREAD

**Issue by Derpyhsi** [zomops/CWP#6]

**Comment by aditee-singh** [comment]
Hi, can I take this?

**Comment by FaryalAjradh** [comment]
Hi, I would like to work on this too. Can you provide more details?

**Comment by Aathira123** [comment]
Hello, Can I please work on this ?

**Comment by Derpyhsi** [comment]
Work together to style the website in anyway you would like :D

**Comment by FaryalAjradh** [comment]
yep sure
