### ISSUE TITLE
Add a code sharing page

### ISSUE THREAD

**Issue by Derpyhsi** [zomops/CWP#7]

**Comment by prnvsan** [comment]
Hello! I would like to work on this! Can you provide me with more details?

**Comment by FaryalAjradh** [comment]
Hi! I would like to work on this too. Please provide more details

**Comment by Derpyhsi** [comment]
The page should let you download code snippets by clicking on a link.

**Comment by FaryalAjradh** [comment]
okay

**Comment by Speedy6451** [comment]
I am working on this
